### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by zhang-jinyi** [artetxem/monoses#12]
Hi,
Sorry to trouble you, but I had this error:

ERROR: compile contrib/sigtest-filter at /home/zhang/data-short/monoses/third-party/moses/scripts/generic/binarize4moses2.perl line 34.
ERROR: compile contrib/sigtest-filter at /home/zhang/data-short/monoses/third-party/moses/scripts/generic/binarize4moses2.perl line 34.
Using SCRIPTS_ROOTDIR: /home/zhang/data-short/monoses/third-party/moses/scripts
Not executable: /home/zhang/data-short/monoses/third-party/moses/bin/moses2 at /home/zhang/data-short/monoses/third-party/moses/scripts/training/mert-moses.pl line 466.
Traceback (most recent call last):
  File "/home/zhang/.pyenv/versions/3.7.2/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'cj-word-smt/tmpou08sq8q/mert/moses.ini' -> 'cj-word-smt/step7/src2trg.it1.moses.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 484, in <module>
    main()
  File "train.py", line 478, in main
    unsupervised_tuning(args)
  File "train.py", line 366, in unsupervised_tuning
    shutil.move(args.tmp + '/mert/moses.ini', config[(src, trg)])
  File "/home/zhang/.pyenv/versions/3.7.2/lib/python3.7/shutil.py", line 577, in move
    copy_function(src, real_dst)
  File "/home/zhang/.pyenv/versions/3.7.2/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/zhang/.pyenv/versions/3.7.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'cj-word-smt/tmpou08sq8q/mert/moses.ini'

Is that the moses2 didn't been compiled?

**Comment by sevilaybayatli** [comment]
hi zhang-jinyi,

I have same problem, did it solve for you, please need help to solve that problem.

**Comment by ningqiuyi** [comment]
I had the same problem , then I replaced moses2 with moses .

**Comment by sevilaybayatli** [comment]
hey!
any idea how to replace  moses2 with moses. Also could you give a link
please?

**Comment by ningqiuyi** [comment]
You just need to replace the scenes2 in the code with the moses in your path, but Moses and Moses2 aren't exactly alike, there's some differences in pruning, stack configuration etc. You can refer to this http://www.statmt.org/ Moses/?n=Site.Moses2

**Comment by toshohirasawa** [comment]
I had the same problem, and I have managed it by installing Moses2.

As Moses does not build Moses2 without specifying `XMLRPC-c` (1.39.12) and `cmph` (2.0), I need to build these dependencies first. 
http://www.statmt.org/moses/?n=Site.Moses2

XMLRPC-c: 1.39.12
cmph: 2.0

Now, I used the command below to build Moses2.
```
./bjam --with-xmlrpc-c=/path/to/xmlrpc --with-cmph=/path/to/cmph -j4
```

For more details, manually execute each command corresponding to each step in `train.py` and you can find actual error messages.

**Comment by shefs0709** [comment]
Hello  toshohirasawa,
Can you tell how to build xmlrpc? Or can you provide some link?
I have tried installing it but getting an error.

**Comment by d-ks** [comment]
I'll leave you with my notes for building Moses. I hope it will be useful to someone else.
This is a build procedure that I obtained through trial and error, relying on toshohirasawa's comment above, 
so please take it at your own risk.
I installed it on my recently set up Ubuntu 20.04.1 LTS.

**XMLRPC-c: 1.39.12**
First, download it from here.
https://sourceforge.net/projects/xmlrpc-c/files/Xmlrpc-c%20Super%20Stable/1.39.12/

If you run configure at this stage, you may get the following message and it may not work.

> We are not building any client XML transport (see earlier messages explaining why), therefore WE WILL NOT BUILD THE CLIENT LIBRARY.　

So, you first install the library.
`sudo apt-get install libcurl4-gnutls-dev`
(reference: https://askubuntu.com/questions/748683/installing-xml-rpc-c)

Then, configure, make and install it.
```
./configure
make
sudo make install
```

**cmph 2.0**
First, download it from here.
https://sourceforge.net/projects/cmph/files/cmph/cmph-2.0.tar.gz

Then, configure, make and install it.
```
./configure
make
sudo make install
```

**Moses**
This is Moses as retrieved by get-third-party.sh.
First, go to `monoses > third-party > moses`.
Make sure you have boost in your system. If you don't have
`sudo apt install libboost-dev libboost-all-dev`

Install libbz2-dev as well, as it may cause bz2-related errors.
`sudo apt-get install libbz2-dev `

Build with the libraries that you have installed above. 
In my case, I ran a command like this.
`./bjam --with-xmlrpc-c=/usr/local --with-cmph=/usr/local/include -j4`

It will take a while, but when you see SUCCESS at the end, it's OK.

**Comment by hcd7434** [comment]
Hello author, I built according to your notes, but the problem is not solved, I don't know what went wrong.
The error is as follows:
ERROR: compile contrib/sigtest-filter at /home/hcd19/moses/monoses/third-party/moses/scripts/generic/binarize4moses2.perl line 34.
ERROR: compile contrib/sigtest-filter at /home/hcd19/moses/monoses/third-party/moses/scripts/generic/binarize4moses2.perl line 34.

**Comment by hcd7434** [comment]
> 您好，
> 很抱歉打扰您，但我遇到了以下错误：
> 
> 错误：在 /home/zhang/data-short/monoses/third-party/moses/scripts/generic/binarize4moses2.perl 第 34 行编译 contrib/sigtest-filter。
> 错误：在 /home/zhang/ 编译 contrib/sigtest-filter data-short/monoses/third-party/moses/scripts/generic/binarize4moses2.perl 第 34 行。
> 使用 SCRIPTS_ROOTDIR：/home/zhang/data-short/monoses/third-party/moses/scripts
> 不可执行：/home/zhang /data-short/monoses/third-party/moses/bin/moses2 位于 /home/zhang/data-short/monoses/third-party/moses/scripts/training/mert-moses.pl 第 466 行。
> 回溯（最近最后调用）：
> 文件“/home/zhang/.pyenv/versions/3.7.2/lib/python3.7/shutil.py”，第 563 行，移动
> os.rename(src, real_dst)
> FileNotFoundError: [Errno 2] 没有这样的文件或目录：'cj-word-smt/tmpou08sq8q/mert/moses.ini' -> 'cj-word-smt/step7/src2trg.it1.moses.ini'
> 
> 在处理上述异常的过程中，又发生了一个异常：
> 
> 回溯（最近一次调用最后一次）：
> 文件“train.py”，第 484 行，在
> main()
> 文件“train.py”，第 478 行，在 main unsupervised_tuning
> (args)
> 文件“train.py”，第 366 行，在 unsupervised_tuning
> Shutil.move(args.tmp + '/mert/moses.ini', config[(src, trg)])
> 文件“/home/zhang/.pyenv/versions/3.7.2/lib/python3.7/shutil. py”，第 577 行，在移动
> copy_function(src, real_dst)
> 文件“/home/zhang/.pyenv/versions/3.7.2/lib/python3.7/shutil.py”，第 263 行，在 copy2
> copyfile(src, dst, follow_symlinks=follow_symlinks)
> 文件“/home/zhang/.pyenv/versions/3.7.2/lib/python3.7/shutil.py”，第 120 行，在
> open(src, 'rb') 作为fsrc 的复制文件中：
> FileNotFoundError: [Errno 2] 没有这样的文件或目录：'cj-word-smt/tmpou08sq8q/mert/moses.ini'
> 
> 那是moses2没有编译吗？

Hello author, has your problem been solved? Can you tell me the solution?
